In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('us_customer_data 2.csv')

In [4]:
df.head(5)

,customer_id,name,email,phone,address,registration_date,loyalty_status
0,1,Michelle Kidd,vayala@example.net,NaN,"USNS Santiago, FPO AE 80872",2025-01-25,Gold
1,2,Brad Newton,taylorcatherine@example.net,(759)518-8536x738,"38783 Oliver Street, West Kristenborough, MT 9...",2023-07-13,Silver
2,3,Larry Torres,dsanchez@example.net,001-323-525-3094x96062,"6845 Steele Turnpike, West Erikabury, UT 37487",2023-08-18,Bronze
3,4,Kimberly Price,jessicaknight@example.com,001-947-633-4224x07930,"1631 Alexis Meadows, Lake Amanda, CA 75179",2024-12-08,Gold
4,5,Matthew Phillips,qwilliams@example.com,001-869-650-5682x8385,"2274 Williams Heights Suite 895, Andersonhaven...",2024-02-03,Gold

In [ ]:
def split_name(name):
    suffixes = [
    "Jr.", "Sr.", "II", "III", "IV", "V", "Esq.", "PhD", "MD", "DDS", "DVM",
    "CPA", "MBA", "MSc", "BSc", "DO", "OD", "RN", "JD", "LLD", "Eng.", "Ret.",
    "CFA", "CM", "OBE", "MBE", "CBE", "KBE", "DBE"
]      
    prefixes = [
    "Mr.", "Mrs.", "Ms.", "Miss", "Dr.", "Prof.", "Rev.", "Sir", "Madam", "Mx.",
    "Master", "Lady", "Dame", "Capt.", "Major", "Col.", "Gen.", "Lt.", "Hon.",
    "Pres.", "Gov.", "Sen.", "Amb.", "Arch.", "Sheikh", "Sultan", "Prince", "Princess"
]
    parts = name.split()
    if len(parts) == 2:
        return pd.Series([parts[0], parts[1], None, None])
    elif len(parts) >= 3:
        for prefix in prefixes:
            if parts[0] == prefix:
                parts.pop(0)
                break
        for suffix in suffixes:
            if parts[-1] == suffix:
                parts.pop()
                break
def count_parts(name):
    return len(name.split())
df['count'] = df['name'].apply(count_parts)

In [9]:

df.query('count > 2')

,customer_id,name,email,phone,address,registration_date,loyalty_status,count
5,6,Darrell Gallagher DVM,larryharris@example.org,+1-971-475-6369x8486,"19887 Brandon Bridge, New Rebecca, MA 94947",2025-03-03,Bronze,3
7,8,Melissa Galloway MD,watsonbenjamin@example.net,+1-593-948-3872,"209 Steven Oval Apt. 022, Mollyhaven, NC 10211",2023-10-06,Bronze,3
17,18,Mr. Ernest Dunn,kelseybrown@example.net,6209840256,"3112 Lydia Freeway Suite 927, South Susan, RI ...",2025-01-27,Gold,3
41,42,Mr. Andrew Austin,heather79@example.com,(698)852-3560,"200 Thomas Flat, South James, MP 96716",2025-06-12,Gold,3
132,133,Elizabeth Williams MD,josephbrown@example.net,001-280-546-5785,"384 Robert Square Suite 381, Port Andreaview, ...",2025-03-28,Gold,3
148,149,Mr. Timothy Mills DDS,xthompson@example.net,349.381.3465x852,"810 Turner Pass Apt. 686, North William, FM 90760",2023-07-07,Gold,4
163,164,Dr. Michelle Washington,snyderdavid@example.org,NaN,"69374 Kevin Falls, New Anthony, NC 01785",2024-05-08,Bronze,3
167,168,Dr. Nicholas Gonzalez,jasonharrington@example.org,001-750-208-3875x36941,"6874 Christopher Village Suite 491, North Scot...",2024-12-04,Silver,3
177,178,Michael Long Jr.,julieproctor@example.com,272-534-2274x27152,"3591 Samantha Circle Suite 117, Bennettburgh, ...",2024-04-26,Silver,3
207,208,Michael Robinson PhD,zjackson@example.net,540-269-1211,"167 Reed Fall Suite 928, Port Arthurtown, NM 1...",2024-03-21,Bronze,3
216,217,Mrs. Laura Hernandez,bclark@example.com,001-621-278-4959x0374,"41669 Alison Keys, Alexanderstad, OK 01044",2024-09-22,Silver,3
240,241,Miguel Pitts MD,patriciaelliott@example.org,001-227-808-2803x26124,"1462 Emily Road, East Blakeport, DC 03297",2023-11-18,Silver,3
280,281,Cameron Davis DDS,ghanson@example.net,562-663-3001,"930 Brown Branch, New Davidmouth, OH 12055",2023-10-11,Bronze,3
365,366,Valerie Norris PhD,smithlinda@example.org,796.973.5104,"PSC 2620, Box 2037, APO AP 84683",2024-01-05,Gold,3
366,367,Jacob Johnson DDS,velasquezwilliam@example.org,247-707-1897,"6098 Mason Plaza Suite 701, West Briannaland, ...",2023-06-20,Silver,3
405,406,Edgar Davis Jr.,hannahleach@example.net,251-445-2970x6329,"5205 Williams Greens, Brownville, MP 88911",2024-08-22,Bronze,3
407,408,Nicole Buchanan MD,hinesamanda@example.net,(729)952-0780,"67112 Smith Brooks Suite 841, New Brian, CA 13657",2024-03-01,Bronze,3
410,411,Nathan Howard MD,jeffreyroberson@example.com,(330)429-0664,"538 Franklin Trail Suite 020, Russellburgh, IL...",2024-06-17,Bronze,3
452,453,Miss Carolyn Gilbert,jrobinson@example.org,NaN,"USS Zhang, FPO AA 18184",2023-10-07,Bronze,3
530,531,Mrs. Ashley Flores MD,pamela91@example.org,+1-974-998-5687,"592 Joseph Points, East Wendyshire, WI 13694",2025-04-29,Silver,4
571,572,Ms. Stephanie Rodriguez MD,NaN,981-524-9535,"11787 Catherine Divide, Russellmouth, CO 67747",2024-07-26,Bronze,4
572,573,Mr. Philip Wood,jerry88@example.com,(668)330-2482,"06774 Jordan Course Apt. 331, West Melissaberg...",2023-11-12,Silver,3
588,589,Ashley Perkins MD,james89@example.org,001-999-916-6501x5853,"8156 Bruce Lakes Apt. 367, Michaelshire, IN 08733",2025-01-18,Silver,3
614,615,David Ramos Jr.,durancharles@example.com,7368601136,"969 Gomez Cape Apt. 332, Port Alejandro, VT 16899",2024-08-19,Silver,3
615,616,Dr. Deborah Miller DDS,lperez@example.org,327-229-8181x51936,"2181 Johnston Groves Apt. 869, Port Megan, MH ...",2024-12-02,Gold,4
651,652,Lisa Walker DDS,jeffreymoore@example.net,308-568-7085x438,"208 Daryl Square, New Judy, GA 57140",2025-04-13,Bronze,3
660,661,Ms. Amanda Mata,rojasscott@example.org,(758)646-6010,"1033 Garcia Plains Apt. 177, New Ianberg, IA 6...",2025-05-03,Gold,3
665,666,Jillian Schwartz DDS,tim50@example.net,001-865-499-7144x53339,"884 Turner Alley Apt. 854, Delacruzstad, SC 11183",2023-11-18,Silver,3
670,671,Mrs. Sarah Harris PhD,ipalmer@example.org,359-931-4436x927,"62861 Arthur Flat, Owenbury, TX 81114",2024-05-02,Gold,4
675,676,Mrs. Brittany Mckee,marynelson@example.org,302-547-1670x056,"USNS Vance, FPO AP 02174",2025-01-03,Gold,3
678,679,Mrs. Sarah Bond,nbrown@example.com,859-410-7966x1387,"72142 Jones Fork, South Christina, NV 05192",2024-09-13,Gold,3
699,700,Miss Crystal Gomez,michael66@example.com,(730)676-5662x5696,"091 Miller Freeway, New John, PW 86274",2024-12-24,Silver,3
711,712,Dr. Jessica Robbins,weeksmichelle@example.com,(739)480-4469x9110,"928 Williams Throughway, Cowanbury, KY 67492",2024-03-30,Silver,3
772,773,Miss Tiffany Ramos,michael88@example.net,9372471191,"495 Saunders Ports, South Brendachester, VA 87499",2024-06-25,Gold,3
778,779,Dr. Darrell Grant,ashleypowell@example.com,001-970-493-8158x757,"01102 Alyssa Viaduct, West Shawnbury, NH 78045",2024-08-29,Bronze,3
782,783,Mrs. Ashley Massey,katherinevillarreal@example.org,(996)451-3263x70456,"62352 Christine Track, East Gregoryport, CO 48352",2024-04-08,Silver,3
834,835,Mrs. Laurie Jennings,NaN,001-701-430-9498x100,"85592 Timothy Walks, Alyssaland, AS 39601",2024-09-25,Bronze,3
843,844,Jacob Williamson PhD,dblanchard@example.net,217-579-2742,"65634 Cruz Cliffs, Cardenasland, AK 29195",2024-08-20,Silver,3
855,856,Amy Parker MD,harriszachary@example.net,525.648.9204,"554 Tina Crescent, Thomasport, ME 19025",2024-03-05,Silver,3
889,890,Stephen Banks DDS,stephensmichelle@example.org,+1-720-294-2341x0222,"677 Shaffer Lake, Hayeshaven, NM 52206",2024-04-18,Bronze,3
936,937,Gregory Delgado III,sandovaljennifer@example.net,822.319.5914x701,"81588 Tiffany Circles Apt. 973, East Danielle,...",2025-03-30,Bronze,3
989,990,Mrs. Alexis Brown,amy77@example.com,NaN,"083 John Lock, East Dennis, NY 30784",2024-03-09,Gold,3
993,994,Mario Odom MD,sheilarobbins@example.org,435.653.7905x38467,"87583 Tabitha Bypass, West Denise, LA 20244",2025-03-24,Silver,3